project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "Axioms to Algorithms"
  description: "Mathematics and Machine Learning from First Principles"
  favicon: assets/favicon.png
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Mathematics"
        href: mathematics/index.qmd
      - text: "Machine Learning"
        href: machine_learning/index.qmd
    right:
      - icon: github
        href: https://github.com/ahmad-sardar
      - icon: linkedin
        href: https://linkedin.com/in/asardar
      - icon: envelope
        href: mailto:ahmad@ahmadsardar.com


format:
  html:
    theme:
      - darkly
      - custom.scss
    toc: true
    toc-location: left
    number-sections: true
    number-offset: -1
    embed-resources: true
    include-in-header: _includes/goatcounter.html
    include-after-body: _includes/navbar_date.html
